<?php

/**
 * A list of mobiles names, You can add some more
 */

$_mobiles = array(
    'alcatel'              => 'Alcatel',
    'amoi'                 => 'Amoi',
    'iphone'               => 'Apple iPhone',
    'ipod'                 => 'Apple iPod Touch',
    'avantgo'              => 'AvantGo',
    'benq'                 => 'BenQ',
    'blackberry'           => 'BlackBerry',
    'hiptop'               => 'Danger Hiptop',
    'digital paths'        => 'Digital Paths',
    'cldc'                 => 'Generic Mobile',
    'mobile'               => 'Generic Mobile',
    'wireless'             => 'Generic Mobile',
    'midp'                 => 'Generic Mobile',
    'j2me'                 => 'Generic Mobile',
    'smartphone'           => 'Generic Mobile',
    'up.browser'           => 'Generic Mobile',
    'cellphone'            => 'Generic Mobile',
    'up.link'              => 'Generic Mobile',
    'ipaq'                 => 'HP iPaq',
    'htc'                  => 'HTC',
    'lg'                   => 'LG',
    'mda'                  => 'MDA',
    'mobileexplorer'       => 'Mobile Explorer',
    'mobilexplorer'        => 'Mobile Explorer',
    'motorola'             => 'Motorola',
    'mot-'                 => 'Motorola',
    'nec-'                 => 'NEC',
    'docomo'               => 'NTT DoCoMo',
    'netfront'             => 'Netfront Browser',
    'nokia'                => 'Nokia',
    'novarra'              => 'Novarra Transcoder',
    'o2'                   => 'O2',
    'cocoon'               => 'O2 Cocoon',
    'obigo'                => 'Obigo',
    'openwave'             => 'Openwave Browser',
    'operamini'            => 'Opera Mini',
    'opera mini'           => 'Opera Mini',
    'palm'                 => 'Palm',
    'elaine'               => 'Palm',
    'palmsource'           => 'Palm',
    'palmscape'            => 'Palmscape',
    'panasonic'            => 'Panasonic',
    'philips'              => 'Philips',
    'playstation portable' => 'PlayStation Portable',
    'spv'                  => 'SPV',
    'sagem'                => 'Sagem',
    'samsung'              => 'Samsung',
    'sanyo'                => 'Sanyo',
    'sendo'                => 'Sendo',
    'sharp'                => 'Sharp',
    'sie-'                 => 'Siemens',
    'ericsson'             => 'Sony Ericsson',
    'sony'                 => 'Sony Ericsson',
    'symbian'              => 'Symbian',
    'series60'             => 'Symbian S60',
    'SymbianOS'            => 'SymbianOS',
    'blazer'               => 'Treo',
    'vario'                => 'Vario',
    'vodafone'             => 'Vodafone',
    'windows ce'           => 'Windows CE',
    'xda'                  => 'XDA',
    'xiino'                => 'Xiino',
    'zte'                  => 'ZTE',
    'ipad'                 => 'iPad'
);

?>